# Generated by Django 4.1.5 on 2023-02-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user',
            new_name='user_id',
        ),
    ]
