# Generated by Django 4.1.5 on 2023-02-04 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_rename_user_tguser_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.CharField(max_length=150, verbose_name='Tg id'),
        ),
    ]
