# Generated by Django 4.1.5 on 2023-02-04 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_alter_tguser_tg_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tguser',
            old_name='user_id',
            new_name='user',
        ),
    ]
